GET  http://127.0.0.1:5212/books

###
POST  http://127.0.0.1:5212/books
Content-Type: application/json

{
    "title": "ShadowOverInnsmouth",
    "authorLastName": "Lovecraft"
}

###
GET  http://127.0.0.1:5212/books/ShadowOverInnsmouth

###
PUT http://127.0.0.1:5212/books/ShadowOverInnsmouth
Content-Type: application/json

{
    "title": "CallofCthulhu",
    "authorLastName": "Lovecraft"
}

###
DELETE http://127.0.0.1:5212/books/ShadowOverInnsmouth