GET  http://127.0.0.1:5212/book/

###
POST  http://127.0.0.1:5212/books/
Content-Type: application/json

{
    "title": "ShadowOverInnsmouth",
    "authorLastName": "Lovecraft"
}

###
GET  http://127.0.0.1:5212/book/ShadowOverInnsmouth

### Not working because can't change the url title
PUT http://127.0.0.1:5212/books/ShadowOverInnsmouth
Content-Type: application/json

{
    "title": "CallofCthulhu",
    "authorLastName": "Lovecraft"
}

###
DELETE http://127.0.0.1:5212/book/ShadowOverInnsmouth